Repository psss/did, pull requests merged in 2020-04, with the labels that each got.

#220 Do not break sorting on merge
  did/stats.py
Labels: enhancement

#222 Simplify Packit config (copr_build no more needed)
  .packit.yaml
Labels: tests

#198 Use scriptrunner issueFunction to speed up things
  did/plugins/jira.py
Labels: enhancement, jira, plugins
