Repository psss/did, pull requests merged in 2021-02, with the labels that each got.

#235 README.rst: fix a typo
  README.rst
Labels: docs

#236 plugins/{git,google}: expand tilde in config path values
  did/plugins/git.py
  did/plugins/google.py
Labels: plugins

#233 base.py: Use none interpolation for ConfigParser
  did/base.py
Labels: config

#225 Enable epel-8 for packit testing
  .packit.yaml
  Makefile
Labels: tests

#237 Add "no prefix" rule to commit message suggestions
  docs/contribute.rst
Labels: docs
